2021-06-14 11:59:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "S_RESULT" が見つかりません
Table "S_RESULT" not found; SQL statement:
insert into s_result values (null, current_date, ?, ? ,? ,?) [42102-199]
2021-06-14 11:59:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "S_RESULT" が見つかりません
Table "S_RESULT" not found; SQL statement:
select result_id, date, icon, user_comment, admin_comment, user_id from s_result WHERE date LIKE ? AND icon LIKE ? AND user_comment LIKE ?  AND admin_comment LIKE ? AND user_id LIKE ? ORDER BY result_id ASC , date ASC [42102-199]
2021-06-14 12:41:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "USER_LOGIN" が見つかりません
Table "USER_LOGIN" not found; SQL statement:
select count(*) from USER_LOGIN  where USER_ID = ? and USER_NAME = ? and USER_PW = ? [42102-199]
2021-06-14 12:41:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "USER_LOGIN" が見つかりません
Table "USER_LOGIN" not found; SQL statement:
select count(*) from USER_LOGIN  where USER_ID = ? and USER_NAME = ? and USER_PW = ? [42102-199]
2021-06-14 12:41:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "USER_LOGIN" が見つかりません
Table "USER_LOGIN" not found; SQL statement:
insert into user_login values (?, ?, ?) [42102-199]
2021-06-14 13:06:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "USER_LOGIN" はすでに存在します
Table "USER_LOGIN" already exists; SQL statement:
--全選択、貼り付けで実行できます

--受講者ログインテーブル作成
create table user_login (
user_id int (10) PRIMARY KEY AUTO_INCREMENT,
user_name varchar (20),
user_pw varchar (20)
) [42101-200]
2021-06-14 13:06:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "ADMIN_LOGIN" はすでに存在します
Table "ADMIN_LOGIN" already exists; SQL statement:
--管理者ログインテーブル
create table admin_login (
admin_id int (10) PRIMARY KEY AUTO_INCREMENT,
admin_name varchar (20),
admin_pw varchar (20)
) [42101-200]
2021-06-14 13:06:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "S_QUESTION" はすでに存在します
Table "S_QUESTION" already exists; SQL statement:
--質問テーブル
create table s_question (
question_id int (10)　PRIMARY KEY AUTO_INCREMENT,
question varchar (100)
) [42101-200]
2021-06-14 13:06:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "S_ANSWER" はすでに存在します
Table "S_ANSWER" already exists; SQL statement:
--回答テーブル
create table s_answer (
question_id int,
answer int (5) NOT NULL,
user_id int,
date char(10) NOT NULL
) [42101-200]
2021-06-14 13:06:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "S_RESULT" はすでに存在します
Table "S_RESULT" already exists; SQL statement:
--診断結果テーブル
create table s_result (
result_id int (10) PRIMARY KEY AUTO_INCREMENT,
date char(10) NOT NULL,
icon varchar(7) NOT NULL,
user_comment varchar (300),
admin_comment varchar (300),
user_id int
) [42101-200]
2021-06-14 13:07:14 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "USER_LOGIN" はすでに存在します
Table "USER_LOGIN" already exists; SQL statement:
--全選択、貼り付けで実行できます

--受講者ログインテーブル作成
create table user_login (
user_id int (10) PRIMARY KEY AUTO_INCREMENT,
user_name varchar (20),
user_pw varchar (20)
) [42101-200]
2021-06-14 13:07:14 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "ADMIN_LOGIN" はすでに存在します
Table "ADMIN_LOGIN" already exists; SQL statement:
--管理者ログインテーブル
create table admin_login (
admin_id int (10) PRIMARY KEY AUTO_INCREMENT,
admin_name varchar (20),
admin_pw varchar (20)
) [42101-200]
2021-06-14 13:07:14 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "S_QUESTION" はすでに存在します
Table "S_QUESTION" already exists; SQL statement:
--質問テーブル
create table s_question (
question_id int (10)　PRIMARY KEY AUTO_INCREMENT,
question varchar (100)
) [42101-200]
2021-06-14 13:07:14 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "S_ANSWER" はすでに存在します
Table "S_ANSWER" already exists; SQL statement:
--回答テーブル
create table s_answer (
question_id int,
answer int (5) NOT NULL,
user_id int,
date char(10) NOT NULL
) [42101-200]
2021-06-14 13:07:14 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: テーブル "S_RESULT" はすでに存在します
Table "S_RESULT" already exists; SQL statement:
--診断結果テーブル
create table s_result (
result_id int (10) PRIMARY KEY AUTO_INCREMENT,
date char(10) NOT NULL,
icon varchar(7) NOT NULL,
user_comment varchar (300),
admin_comment varchar (300),
user_id int
) [42101-200]
2021-06-14 13:08:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列 "question_id" が見つかりません
Column "question_id" not found [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3188)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3287)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:350)
	at dao.user_loginDao.select(user_loginDao.java:123)
	at test.user_loginDaoTest.main(user_loginDaoTest.java:22)
2021-06-15 14:22:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: パラメータ "parameterIndex" に対する値 "1" が不正です
Invalid value "1" for parameter "parameterIndex" [90008-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:587)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:280)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1573)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:427)
	at dao.s_questionDao.select(s_questionDao.java:50)
	at test.s_questionTest.main(s_questionTest.java:16)
2021-06-15 14:22:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: パラメータ "parameterIndex" に対する値 "2" が不正です
Invalid value "2" for parameter "parameterIndex" [90008-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:587)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:280)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1573)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:427)
	at dao.s_questionDao.select(s_questionDao.java:63)
	at test.s_questionTest.main(s_questionTest.java:16)
